<div class="content-wrapper dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <section class="content dw-overflow">
        <?php View::notify(); ?>
    <div class="box box-primary">
        <div class="box-body">

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="form-group">
            <div class="col-md-6">
                <?php echo DwForm::text('backup.denominacion', array('class'=>'form-control input-xxlarge input-required input-alphanum mask-alphanum show-error'), NULL, 'Denominación'); ?>
            </div>
        </div>

        <div class="col-md-12 form-group">
            <div class="form-actions">
                <?php echo DwButton::save('Crear copia de seguridad'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>
</div>
</div>
</section>
</div>