<div class="content-wrapper dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>
    

    <section class="content dw-overflow">
        <?php View::notify(); ?>
    <div class="box box-primary">
        <div class="box-body">

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwButton::report("auditoria/listar/$fecha/", 'html', 'Reporte de auditorías', 'imprimir'); ?>
        </div>
    </div>

    <div class="dw-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed">
            <thead>
                <tr>
                    <th class="no-responsive dw-text-middle" style="width: 15px;">NUM</th>
                    <th class="no-responsive dw-text-middle">FECHA</th>
                    <th class="no-responsive dw-text-middle">TIPO</th>
                    <th class="no-responsive dw-text-middle">USUARIO</th>
                    <th class="no-responsive dw-text-middle">IP</th>
                    <th class="no-responsive dw-text-center">DESCRIPCION</th>
                </tr>
            </thead>
            <tbody>
                <?php if($audits->items) { ?>
                    <?php foreach($audits->items as $audit): ?>
                    <tr>
                        <td><?php echo $audits->counter; ?></td>
                        <td><?php echo $audit['fecha']; ?></td>
                        <td>
                            <?php if($audit['tipo'] == 'DANGER' OR $audit['tipo'] == 'WARNING') { ?>
                                <span class="label label-danger"><?php echo $audit['tipo']; ?></span>
                            <?php } else if($audit['tipo'] == 'WARNING' OR $audit['tipo'] == 'DANGER' OR $audit['tipo'] == 'SUCCESS') { ?>
                                <span class="label label-warning"><?php echo $audit['tipo']; ?></span>
                            <?php } else if($audit['tipo'] == 'SUCCESS' OR $audit['tipo'] == 'INFO') { ?>
                                <span class="label label-info"><?php echo $audit['tipo']; ?></span>
                            <?php } else { ?>
                                <span class="label label-default"><?php echo $audit['tipo']; ?></span>
                            <?php } ?>
                        </td>
                        <td><?php echo $audit['usuario']; ?></td>
                        <td><?php echo $audit['ip']; ?></td>
                        <td><?php echo $audit['descripcion']; ?></td>
                    </tr>
                    <?php $audits->counter++; ?>
                    <?php endforeach; ?>
                <?php } ?>
            </tbody>

        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$audits, 'url'=>"sistema/sucesos/listar/$fecha/")); ?>
</div>
</div>
</section>
</div>