<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-sm-3 address wow fadeInUp" data-wow-duration="2s" data-wow-delay=".1s">
				<h1>Información de contacto</h1>
				<address>
					<p><i class="fa fa-home pr-10"></i>Dirección: Urb. Mata de Coco</p>
					<p><i class="fa fa-globe pr-10"></i>Ocumare del Tuy, Mir. Venezuela </p>
					<p><i class="fa fa-mobile pr-10"></i>Celular : (0424) 140-3604 </p>
					<p><i class="fa fa-phone pr-10"></i>Teléfono : (0426) 112-6549 </p>
					<p><i class="fa fa-envelope pr-10"></i>Email :   <a href="mailto:info@solucionessl.com.ve">info@solucionessl.com.ve</a></p>
				</address>
			</div>
			<div class="col-lg-3 col-sm-3 wow fadeInUp" data-wow-duration="2s" data-wow-delay=".3s">
				<h1>últimos tweet</h1>
				<div class="tweet-box">
					<i class="fa fa-twitter"></i>
						<em>
							Please follow
							<a href="javascript:;">@example</a>for all future updates of us!
							<a href="javascript:;">twitter.com/acme</a>
						</em>
				</div>
				<div class="tweet-box">
					<i class="fa fa-twitter"></i>
					<em>
						Please follow
						<a href="javascript:;">@example</a>
						for all future updates of us!
						<a href="javascript:;">twitter.com/acme</a>
					</em>
				</div>
				<div class="tweet-box">
					<i class="fa fa-twitter"></i>
					<em>
						Please follow
						<a href="javascript:;">@example</a>
						for all future updates of us!
						<a href="javascript:;">twitter.com/acme</a>
					</em>
				</div>
			</div>
			<div class="col-lg-3 col-sm-3">
				<div class="page-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".5s">
					<h1>Nuestra compañía</h1>
					<ul class="page-footer-list">
						<li><i class="fa fa-angle-right"></i><a href="/acerca_de">Acerca de Nosotros</a></li>
						<li><i class="fa fa-angle-right"></i><a href="/soporte">Soporte</a></li>
						<li><i class="fa fa-angle-right"></i><a href="/contacto">Contacto</a></li>
						<li><i class="fa fa-angle-right"></i><a href="/legales/privacidad_cookies">Privacidad y Cookies</a></li>
						<li><i class="fa fa-angle-right"></i><a href="/contratando">Estamos Contratando</a><li>
						<li><i class="fa fa-angle-right"></i><a href="/legales/aviso_legal">Aviso Legal</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-sm-3">
				<div class="text-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".7s">
					<h1>Chat en línea</h1>
					<p>¿Nesecita ayuda? Chatee con uno de nuestros operadores en línea y se le dará la ayuda necesaria.</p>
					<p>
						<span id='liveadmin'></span>
					</p>
					<p>
						<h2></h2>
					</p>
				</div>
			</div>
		</div>
	</div>
</footer>
<!-- footer end -->
<!--small footer start -->
<footer class="footer-small">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-sm-4 pull-right">
				<ul class="social-link-footer list-unstyled">
					<li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".1s"><a href="#"><i class="fa fa-facebook"></i></a></li>
					<li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".2s"><a href="#"><i class="fa fa-google-plus"></i></a></li>
					<li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".3s"><a href="#"><i class="fa fa-linkedin"></i></a></li>
					<li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".4s"><a href="#"><i class="fa fa-twitter"></i></a></li>
					<li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".5s"><a href="#"><i class="fa fa-youtube"></i></a></li>
				</ul>
			</div>
			<div class="col-md-6">
				<div class="copyright">
					<p>&copy; Copyright 2013-2015 - <!-- Soluciones SL. --> <?php echo Html::img('logo-footer.png') ?> - Todos los derechos reservados.</p>
				</div>
			</div>
		</div>
	</div>
</footer>
<!--small footer end-->

<?php echo Tag::js('jquery-1.11.3').PHP_EOL; ?>
<?php echo Tag::js('bootstrap.min').PHP_EOL; ?>
<?php echo Tag::js('hover-dropdown').PHP_EOL; ?>
<?php echo Tag::js('jquery.flexslider').PHP_EOL; ?>
<?php echo Tag::js('jquery.bxslider').PHP_EOL; ?>
<?php echo Tag::js('jquery.parallax-1.1.3').PHP_EOL; ?>
<?php echo Tag::js('owl.carousel').PHP_EOL; ?>
<?php echo Tag::js('jquery.easing.min').PHP_EOL; ?>
<?php echo Tag::js('link-hover').PHP_EOL; ?>
<?php echo Tag::js('superfish').PHP_EOL; ?>
<?php echo Tag::js('parallax-slider/jquery.cslider').PHP_EOL; ?>
<?php echo Tag::js('wow.min').PHP_EOL; ?>
<?php echo Tag::js('jquery/jquery.kumbiaphp').PHP_EOL; ?>
<?php echo Tag::js('jquery/jquery.keyfilter').PHP_EOL; ?>
<?php echo Tag::js('jquery/jquery.dwload').PHP_EOL; ?>
<?php echo Tag::js('vendors/jsspin.min').PHP_EOL; ?>
<?php echo Tag::js('jquery/jquery.spin').PHP_EOL; ?>

	<script type="text/javascript">
		wow = new WOW(
				{
					boxClass: 'wow',
					animateClass: ' animated',
					offset: 0
				}
				) 
					wow.init();
	</script>

<script type="text/javascript">
	$(function() {

		$('#da-slider').cslider({
			autoplay    : true,
			bgincrement : 100
		});

	});
</script>

<?php echo Tag::js('common-scripts'); ?>

<script type="text/javascript">
		jQuery(document).ready(function() {


		$('.bxslider1').bxSlider({
			minSlides: 5,
			maxSlides: 6,
			slideWidth: 360,
			slideMargin: 2,
			moveSlides: 1,
			responsive: true,
			nextSelector: '#slider-next',
			prevSelector: '#slider-prev',
			nextText: 'Adelante →',
			prevText: '← Atras'
		});

		});


</script>

<script type="text/javascript">

	$('a.info').tooltip();

	$(window).load(function() {
		$('.flexslider').flexslider({
			animation: "slide",
			start: function(slider) {
				$('body').removeClass('loading');
			}
		});
	});

	$(document).ready(function() {
		$("#owl-demo").owlCarousel({
			items : 4
		});
	});

	jQuery(document).ready(function(){
		jQuery('ul.superfish').superfish();
	});

</script>

<script type="text/javascript">
	$(document).ready(function() {
		url = (window.location.hash.lenth >1) ? window.hash : window.location.pathname;
		url = url.split('order')[0].split('pag')[0];
		var activePageSubMenuId;
		var activePageMainMenuElement;
		$(".subnav").each(function (i) {
			if(!$(this).hasClass("hidden")) {
				activePageSubMenuId = $(this).attr("id");
			} else {
				contenedor = $(this).attr('id');
				$(this).find('a').each(function(i) {
					if(url==$(this).attr('href')) {
						$('#'+contenedor).removeClass('hidden');
						$(this).parent().addClass('active');
						$('[data-filter="'+contenedor+'"]').each(function () {
							$(this).parent().addClass('main-nav-arrow active');
							$(this).removeClass('hidden');
							return false;
						});
						return false;
					}
				});
			}
		});
		$(".dropdown-menu").each(function(i) {
			$(this).find('a').each(function(i){
				if(url==$(this).attr('href')) {
					$(this).parent().addClass('active');
					return false;
				}
			});
		});
		$('.dropdown-menu a').on('click', function(){
			este = $(this);
			$(".dropdown-menu a").each(function(i){
				$(this).parents().removeClass('active');
			});
			este.parent().addClass('active');
		});
		//Activa el menú actual
		$(".main-menu-link").each(function (i) {
			if($(this).parent().hasClass("active")){
				activePageMainMenuElement = $(this).attr("id");
			}
		});
		// Habilita el submenú
		$(".main-menu-link").on('click', function(){
			var submenu = $("#" +$(this).attr("data-filter"));
			$(".subnav").each(function (i) {
				$(this).attr("class","subnav hidden");
			});
			submenu.attr("class", "subnav");
			$(".main-menu-link").each(function(i) {
			   $(this).parent().removeClass("main-nav-arrow");
			});
			$(this).parent().addClass("main-nav-arrow");
		});
		//Activa el submenú actual
		$('.subnav a').on('click', function(){
			este = $(this);
			$(".subnav li").removeClass('active');
			$(".main-menu-link").parent().removeClass('active');
			este.parent().addClass('active');
			$('.main-nav-arrow').addClass('active');
			//este.parents('div.subnav').removeClass('hidden');
			//$(this).parent().addClass("main-nav-arrow");
		});
		//Activa el menú manualmente
		$('.main-menu-link').on('click', function(){
		   if($(this).attr('href').length > 2) {
			   $(".main-menu-link").parent().removeClass('active');
			   $(this).parent().addClass('active');
		}
		});
		});
	$(function() {
		$("[rel=tooltip]").tooltip();
	});
</script>

<?php echo DwDialog::alert('Se ha producido un error en la validación del formulario.', 'subtext: Verifica los datos e intenta nuevamente.', 'title: Formulario incorrecto', 'name: errorForm'); ?>
<?php if(PRODUCTION) { ?>
<?php echo DwDialog::alert('Se ha generado la siguiente excepción: <br /><span id="dw-error-ajax"></span>.', 'title: Oops! hemos realizado algo mal.', 'name: errorAjax'); ?>
<?php } else { ?>
<?php echo DwDialog::alert('Se ha generado la siguiente excepción: <br /><span id="dw-error-ajax"></span>.<br /><span id="dw-info-error-ajax"></span>', 'title: Oops! hemos realizado algo mal.', 'name: errorAjax'); ?>
<?php } ?>
<?php echo DwDialog::alert('Usted no posee los permisos necesarios para realizar esta acción.', 'title: Acceso denegado', 'name: accessControl'); ?>