<!--header start-->
<header class="head-section">
	<div class="navbar navbar-default navbar-static-top container">
		<div class="navbar-header">
			<button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/"><?= Html::img('logo.png', 'Soluciones SL logo')  ?></a>
		</div>
		<?php View::partial('menu') ?>
	</div>
</header>