<div class="navbar-collapse collapse">
	<ul class="nav navbar-nav">
		<li class="dropdown">
			<a href="/">Home</a>
		</li>
		<li class="dropdown">
		<a class="dropdown-toggle" data-close-others="false" data-delay="0" data-hover="dropdown" data-toggle="dropdown" href="/servicios_web">Servicios Web <i class="fa fa-angle-down"></i></a>
		<ul class="dropdown-menu">
			<li><a href="/servicios_web/diseno_web">Dise&ntilde;o Web</a></li>
			<li><a href="/servicios_web/aplicaciones_web">Aplicaciones Web</a></li>
		</ul>
		</li>
		<li class="dropdown">
		<a class="dropdown-toggle" data-close-others="false" data-delay="0" data-hover="dropdown" data-toggle="dropdown" href="/hosting">Hosting <i class="fa fa-angle-down"></i></a>
		<ul class="dropdown-menu">
			<li><a href="">Registro de Dominios</a></li>
			<li><a href="">Alojamiento Web</a></li>
			<li><a href="">Correo Corporativo</a></li>
		</ul></li>
		<li class="dropdown">
		<a class="dropdown-toggle" data-close-others="false" data-delay="0" data-hover="dropdown" data-toggle="dropdown" href="/servicios_it">Servicios IT <i class="fa fa-angle-down"></i></a>
		<ul class="dropdown-menu">
			<li><a href="/servicios_it/consultoria">Consultoría</a></li>
			<li><a href="/servicios_it/formacion">Formación</a></li>
			<li><a href="/servicios_it/soporte_actualizacion">Soporte y Actualización</a></li>
			<li><a href="/servicios_it/outsourcing_it">Outsourcing IT</a></li>
		</ul></li>
		<li><a href="/contacto">Contacto</a></li>
		<li><input class="form-control search" placeholder=" Buscar..." type="text"></li>
		<li><a href="/sistema/login/entrar/"><i class="fa fa-user"></i></a></li>
	</ul>
</div>
