<!-- Sequence Modern Slider -->
<div id="da-slider" class="da-slider">
	<div class="da-slide">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2><i>CLEAN &amp; FRESH</i>
						<br>
						<i>RESPONSIVE</i>
						<br>
						<i>DESIGN</i>
					</h2>
					<p>
						<i>Lorem ipsum dolor amet</i>
						<br />
						<i>veniam omnis</i>
					</p>
					<a href="#" class="btn btn-primary btn-lg da-link">
						Read more
					</a>
					<div class="da-img">
						<?=Html::img('slider/2.png', 'imagen01') ?>
					</div>
				</div>
			</div>
		</div>
	</div>


	<div class="da-slide">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2>
						<i>RESPONSIVE VIDEO</i>
						<br />
						<i>SUPPORT AND</i>
						<br />
						<i>MANY MORE</i>
					</h2>
					<p>
						<i>Lorem ipsum dolor amet</i>
						<br />
						<i>tempor incididunt ut</i>
					</p>
					<a href="#" class="btn btn-primary btn-lg da-link">
						Read more
					</a>
					<div class="da-img">
						<?php echo Html::img('slider/1.png', 'imagen02') ?>
					</div>
				</div>
			</div>
		</div>
	</div>


	<div class="da-slide">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2>
						<i>USING BEST WEB</i>
					</br>
					<i>SOLUTIONS WITH</i>
				</br>
				<i>HTML5/CSS3</i>
			</h2>
			<p>
				<i>Lorem ipsum dolor amet</i>
				<br />
				<i>tempor incididunt ut</i>
				<br />
				<i>veniam omnis </i>
			</p>
			<a href="#" class="btn btn-primary btn-lg da-link">
				Read more
			</a>
			<div class="da-img">
				<?php echo Html::img('slider/3.png', 'imagen03') ?>
			</div>
		</div>
	</div>
</div>
</div>

<nav class="da-arrows">
	<span class="da-arrows-prev">
	</span>
	<span class="da-arrows-next">
	</span>
</nav>
</div>