<div class="content-wrapper dw-shell-view">
  
        <?php View::process($page_module, $page_title, $set_title); ?>

    <section class="content dw-overflow">
        <?php View::notify(); ?>
    <div class="box box-primary">
        <div class="box-body">

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="form-group">
            <div class="col-md-6">
                <?php echo DwForm::date('log', array('class'=>'form-control input-required mask-date input-date show-errors'), date("Y-m-d"), 'Día'); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="form-actions">
                <?php echo DwButton::submit('Listar logs', 'check', NULL, 'mostrar'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>


    <?php echo DwForm::close(); ?>


</div>
</div>
</section>
</div>