<div class="content-wrapper">

	<?php View::process($page_module, $page_title, $set_title); ?>
    

	<section class="content">
		<?php View::notify(); ?>
		<div class="box box-primary">
			<div class="box-body">
				<?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')).PHP_EOL; ?>

				<div class="form-group">
					<div class="col-md-6">
						<?php echo DwForm::text('menu.menu', array('class'=>'form-control input-required mask-alphanum show-error'), NULL, 'Título').PHP_EOL; ?>
					</div>
					<div class="col-md-6">
						<?php echo DwForm::dbSelect('menu.menu_id', 'menu', array('sistema/menu', 'getListadoMenu', Menu::ACTIVO), 'Ninguno', array('class'=>'form-control mask-pint show-errors'), NULL, 'Menú padre').PHP_EOL; ?>
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-8">
						<?php echo DwForm::dbSelect('menu.recurso_id', 'recurso', array('sistema/recurso', 'getListadoRecurso', Recurso::ACTIVO), 'Ninguno', array('class'=>'form-control mask-pint show-errors'), NULL, 'Recurso').PHP_EOL; ?>
					</div>
					<div class="col-md-4">
						<?php echo DwForm::text('menu.posicion', array('class'=>'form-control mask-pint show-error'), NULL, 'Posición').PHP_EOL; ?>
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-4">
						<?php echo DwForm::text('menu.icono', array('class'=>'form-control mask-alphanum show-error'), NULL, 'Icono a mostrar').PHP_EOL; ?>
					</div>
					<div class="col-md-4">
						<?php echo DwForm::text('menu.url', array('class'=>'form-control show-error'), NULL, 'URL').PHP_EOL; ?>
					</div>
					<div class="col-md-4">
						<?php echo DwForm::select('menu.visibilidad', array(Menu::BACKEND=>'Backend', Menu::FRONTEND=>'Frontend'), array('class'=>'form-control required show-errors'), Menu::BACKEND, 'Visibilidad').PHP_EOL; ?>
					</div>
				</div>
			</div>
			<div class="form-group clearfix">
				<div class="form-actions">
					<?php echo DwButton::save('Guardar menú').PHP_EOL; ?>
					<?php echo DwButton::reset('form').PHP_EOL; ?>
					<?php echo DwButton::cancel('sistema/menu/listar/').PHP_EOL; ?>
				</div>
			</div>

			<?php echo DwForm::close(); ?>

			
		</div>
	</section>
</div>

<script type="text/javascript" >
	$(function(){
		$("#menu_recurso_id").on('change',function(){
			var recurso = $('option:selected',this).text();
			$("#menu_url").val(recurso.replace('/*','/'));
		});
	});
</script>