<div class="content-wrapper">

    <?php View::process($page_module, $page_title, $set_title); ?>
    

<section class="content">
        <?php View::notify(); ?>
        <div class="box box-primary">
        <div class="box-body">

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'form-group dw-validate')); ?>

        <div class="form-group">
            <div class="col-md-6">
                <?php echo DwForm::text('menu.menu', array('class'=>'form-control input-required mask-alphanum show-error'), $menu->menu, 'Título'); ?>
            </div>
            <div class="col-md-6">
                <?php echo DwForm::dbSelect('menu.menu_id', 'menu', array('sistema/menu', 'getListadoMenu', Menu::ACTIVO), 'Ninguno', array('class'=>'form-control mask-pint show-errors'), $menu->menu_id, 'Menú padre'); ?>
            </div>
            <div class="col-md-8">
                <?php echo DwForm::dbSelect('menu.recurso_id', 'recurso', array('sistema/recurso', 'getListadoRecurso', Recurso::ACTIVO), 'Ninguno', array('class'=>'form-control mask-pint show-errors'), $menu->recurso_id, 'Recurso'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-4">
                <?php echo DwForm::text('menu.posicion', array('class'=>'form-control mask-pint show-error'), $menu->posicion, 'Posición'); ?>
            </div>
            <div class="col-md-4">
                <?php echo DwForm::text('menu.icono', array('class'=>'form-control mask-alphanum show-error'), $menu->icono, 'Icono a mostrar'); ?>
            </div>
            <div class="col-md-4">
                <?php echo DwForm::text('menu.url', array('class'=>'form-control show-error'), $menu->url, 'URL'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-4">
                <?php echo DwForm::select('menu.visibilidad', array(Menu::BACKEND=>'Backend', Menu::FRONTEND=>'Frontend'), array('class'=>'form-control input-required show-errors'), $menu->visibilidad, 'Visibilidad'); ?>
            </div>
            <?php echo DwForm::hiddenKey('menu.id', $menu->id)?>
        </div>
        </div>

        <div class="form-action">
            <div class="form-action">
                <?php echo DwButton::save('Guardar menu'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel('sistema/menu/listar/'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>
    </div>
 </section>
</div>
