 <!DOCTYPE html>
<html lang="es">
<head>
	<?php Html::headLinkResource ('img/favicon.png' , "rel='shortcut icon',type='image/xicon'"); ?>
	<?php echo Html :: includeHeadLinks () ?>
	<title><?php echo Config::get('config.application.name'); ?> | <?php echo $page_title; ?></title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta charset="<?php echo APP_CHARSET; ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="robots" content="noindex,nofollow" />

	<?php Tag::css('bootstrap/bootstrap.min') ?>
	<?php Tag::css('font-awesome/font-awesome.min') ?>
	<?php Tag::css('admin/Admin.min') ?>
	<?php Tag::css('admin/skins/_all-skins.min') ?>
	<?php Tag::css('admin/skins/skin-blue.min') ?>
	<?php Tag::css('blue') ?>
	<?php Tag::css('morris') ?>
	<?php Tag::css('datepicker3') ?>
	<?php Tag::css('bootstrap3-wysihtml5.min') ?>
	<?php Tag::css('daterangepicker-bs3') ?>
	<?php Tag::css('jquery-jvectormap-1.2.2') ?>
	<?php Tag::css('datatables/dataTables.bootstrap') ?>

	<?= Html::includeCss() ?>
	<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	<?php echo Tag::js('parallax-slider/modernizr.custom.28468'); ?>
	<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
	<?php View::partial('backend/header'); ?>
	<?php View::content() ?>
	<?php View::partial('backend/footer'); ?>
</div>
</body>
</html>
