<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>mikrotik/planes/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"mikrotik/planes/listar/"
        });
    });
</script>

<div class="content-wrapper dw-shell-view">
  
        <?php View::process($page_module, $page_title, $set_title); ?>

    <section class="content dw-overflow">
        <?php View::notify(); ?>
    <div class="box box-primary">
        <div class="box-body">

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("mikrotik/planes/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th class="col-collapse" data-search="planes">Plan</th>
                    <th class="col-collapse" data-search="uptime">Tiempo de uso</th>
                    <th class="btn-actions no-responsive" style="width: 150px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($lista->getAll() as $item) : ?>
                
                <tr>
                    <td><?php echo $item->getProperty('name') ?></td>
                    <td><?php echo $item->getProperty('validity') ?></td>
                    <td>
                            <?php echo DwHtml::buttonTable('Ver usuario', "mikrotik/planes/ver/", NULL, 'warning', 'search'); ?>
                            <?php echo DwHtml::buttonTable('Modificar usuario', "mikrotik/planes/editar/", NULL, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Reactivar usuario', "mikrotik/planes/estado/reactivar/", NULL, 'danger', 'flag'); ?>
                        </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
    </div>
    </div>
    </section>
</div>