<script type="text/javascript">
    var ciudades = <?php echo $ciudades; ?>;
    $(function() {
        $('#ciudad').typeahead({
                source: ciudades, items:5
        });
    });
</script>

<div class="content-wrapper dw-shell-view">

     <?php View::process($page_module, $page_title, $set_title); ?>

    <section class="content dw-overflow">
        <?php View::notify(); ?>
    <div class="box box-primary">
        <div class="box-body">

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="form-group">
            <div class="col-md-12">
                <?php echo DwForm::text('sucursal.sucursal', array('class'=>'form-control input-xxlarge input-required input-alphanum mask-alphanum show-error'), NULL, 'Nombre de la sucursal'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6">
                <?php echo DwForm::text('sucursal.direccion', array('class'=>'form-control input-xxlarge input-required input-alphanum mask-alphanum show-error'), NULL, 'Dirección'); ?>
            </div>
            <div class="col-md-6">
                <?php echo DwForm::text('ciudad', array('class'=>'form-control input-xxlarge input-required input-alphanum mask-alphanum show-error', 'autocomplete'=>'off'), NULL, 'Ciudad'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-4">
                <?php echo DwForm::tel('sucursal.celular', array('class'=>'form-control input-numeric mask-pint show-error'), NULL, 'Celular'); ?>
            </div>
            <div class="col-md-4">
                <?php echo DwForm::tel('sucursal.telefono', array('class'=>'form-control input-numeric mask-pint show-error'), NULL, 'Teléfono'); ?>
            </div>
            <div class="col-md-4">
                <?php echo DwForm::tel('sucursal.fax', array('class'=>'form-control input-numeric mask-pint show-error'), NULL, 'Fax'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar sucursal'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>
</div>
</div>
</section>
</div>