<div class="content-wrapper dw-shell-view">

     <?php View::process($page_module, $page_title, $set_title); ?>

    <section class="content dw-overflow">
        <?php View::notify(); ?>
        <div class="row">
		<div class="col-md-3 col-sm-6 col-xs-12">
		  <div class="info-box bg-aqua">
		 	<span class="info-box-icon"><i class="fa fa-pie-chart"></i></span>

			<div class="info-box-content">
			  <span class="info-box-text">Memoria Libre</span>
			  <span class="info-box-number"><?php echo(number_format($free_mem, 0, ',', '.')) ?> Kb</span>

			  <div class="progress">
				<div class="progress-bar" style="width: 70%"></div>
			  </div>
				  <span class="progress-description">
					70% Increase in 30 Days
				  </span>
			</div>
			<!-- /.info-box-content -->
		  </div>
		  <!-- /.info-box -->
		</div>
		<!-- /.col -->
		<div class="col-md-3 col-sm-6 col-xs-12">
		  <div class="info-box bg-green">
		 	<span class="info-box-icon"><i class="fa fa-hdd-o"></i></span>

			<div class="info-box-content">
			  <span class="info-box-text">Espacio Libre</span>
			  <span class="info-box-number"><?php echo(number_format($free_hdd, 0, ' ', '.')) ?> Kb</span>

			  <div class="progress">
				<div class="progress-bar" style="width: 70%"></div>
			  </div>
				  <span class="progress-description">
					70% Increase in 30 Days
				  </span>
			</div>
			<!-- /.info-box-content -->
		  </div>
		  <!-- /.info-box -->
		</div>
		<!-- /.col -->
		<div class="col-md-3 col-sm-6 col-xs-12">
		  <div class="info-box bg-yellow">
		 	<span class="info-box-icon"><i class="fa fa-area-chart"></i></span>

			<div class="info-box-content">
			  <span class="info-box-text">Uso del CPU</span>
			  <span class="info-box-number"><?php echo $cpu ?> %</span>

			  <div class="progress">
				<div class="progress-bar" style="width: 70%"></div>
			  </div>
				  <span class="progress-description">
					70% Increase in 30 Days
				  </span>
			</div>
			<!-- /.info-box-content -->
		  </div>
		  <!-- /.info-box -->
		</div>
		<!-- /.col -->
		<div class="col-md-3 col-sm-6 col-xs-12">
		  <div class="info-box bg-red">
		 	<span class="info-box-icon"><i class="icon ion-thermometer"></i></span>

			<div class="info-box-content">
			  <span class="info-box-text">Temperatura</span>
			  <span class="info-box-number"><?php echo $therm ?> 41 &deg;C</span>

			  <div class="progress">
				<div class="progress-bar" style="width: 70%"></div>
			  </div>
				  <span class="progress-description">
					70% Increase in 30 Days
				  </span>
			</div>
			<!-- /.info-box-content -->
		  </div>
		  <!-- /.info-box -->
		</div>
		<!-- /.col -->
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">Usuarios Activos</h3>
				</div>
				<div class="box-body">
					<table class="table table-bordered">
						<thead>
							<tr>
								<th>Usuario</th>
								<th>Direccion IP</th>
								<th>Tiempo Online</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($activos->getAll() as $activo) : ?>
								<tr>
									<td><?php echo $activo->getProperty('name') ?></td>
									<td><?php echo $activo->getProperty('address') ?></td>
									<td><?php echo $activo->getProperty('uptime') ?></td>
								</tr>
								<?php $activos->counter++; ?>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="dw-overflow">
	</div>
</section>  
</div>