<footer class="main-footer">
	<div class="pull-right hidden-xs">
		<b>Version</b> <?php echo Config::get('config.custom.app_version') ?>
	</div>
	<strong>&copy; Copyright 2013-2015 - <!-- Soluciones SL. --> </strong><?php echo Html::img('logo-footer.png') ?> Todos los derechos reservados.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
	<!-- Create the tabs -->
	<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
		<li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
		<li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
	</ul>
	<!-- Tab panes -->
	<div class="tab-content">
		<!-- Home tab content -->
		<div class="tab-pane" id="control-sidebar-home-tab">
			<h3 class="control-sidebar-heading">Recent Activity</h3>
			<ul class="control-sidebar-menu">
				<li>
					<a href="javascript::;">
						<i class="menu-icon fa fa-birthday-cake bg-red"></i>
						<div class="menu-info">
							<h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
							<p>Will be 23 on April 24th</p>
						</div>
					</a>
				</li>
				<li>
					<a href="javascript::;">
						<i class="menu-icon fa fa-user bg-yellow"></i>
						<div class="menu-info">
							<h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
							<p>New phone +1(800)555-1234</p>
						</div>
					</a>
				</li>
				<li>
					<a href="javascript::;">
						<i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
						<div class="menu-info">
							<h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
							<p>nora@example.com</p>
						</div>
					</a>
				</li>
				<li>
					<a href="javascript::;">
						<i class="menu-icon fa fa-file-code-o bg-green"></i>
						<div class="menu-info">
							<h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
							<p>Execution time 5 seconds</p>
						</div>
					</a>
				</li>
			</ul><!-- /.control-sidebar-menu -->

			<h3 class="control-sidebar-heading">Tasks Progress</h3>
			<ul class="control-sidebar-menu">
				<li>
					<a href="javascript::;">
						<h4 class="control-sidebar-subheading">
							Custom Template Design
							<span class="label label-danger pull-right">70%</span>
						</h4>
						<div class="progress progress-xxs">
							<div class="progress-bar progress-bar-danger" style="width: 70%"></div>
						</div>
					</a>
				</li>
				<li>
					<a href="javascript::;">
						<h4 class="control-sidebar-subheading">
							Update Resume
							<span class="label label-success pull-right">95%</span>
						</h4>
						<div class="progress progress-xxs">
							<div class="progress-bar progress-bar-success" style="width: 95%"></div>
						</div>
					</a>
				</li>
				<li>
					<a href="javascript::;">
						<h4 class="control-sidebar-subheading">
							Laravel Integration
							<span class="label label-warning pull-right">50%</span>
						</h4>
						<div class="progress progress-xxs">
							<div class="progress-bar progress-bar-warning" style="width: 50%"></div>
						</div>
					</a>
				</li>
				<li>
					<a href="javascript::;">
						<h4 class="control-sidebar-subheading">
							Back End Framework
							<span class="label label-primary pull-right">68%</span>
						</h4>
						<div class="progress progress-xxs">
							<div class="progress-bar progress-bar-primary" style="width: 68%"></div>
						</div>
					</a>
				</li>
			</ul><!-- /.control-sidebar-menu -->

		</div><!-- /.tab-pane -->
		<!-- Stats tab content -->
		<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
		<!-- Settings tab content -->
		<div class="tab-pane" id="control-sidebar-settings-tab">
			<form method="post">
				<h3 class="control-sidebar-heading">General Settings</h3>
				<div class="form-group">
					<label class="control-sidebar-subheading">
						Report panel usage
						<input type="checkbox" class="pull-right" checked>
					</label>
					<p>
						Some information about this general settings option
					</p>
				</div><!-- /.form-group -->

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Allow mail redirect
						<input type="checkbox" class="pull-right" checked>
					</label>
					<p>
						Other sets of options are available
					</p>
				</div><!-- /.form-group -->

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Expose author name in posts
						<input type="checkbox" class="pull-right" checked>
					</label>
					<p>
						Allow the user to show his name in blog posts
					</p>
				</div><!-- /.form-group -->

				<h3 class="control-sidebar-heading">Chat Settings</h3>

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Show me as online
						<input type="checkbox" class="pull-right" checked>
					</label>
				</div><!-- /.form-group -->

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Turn off notifications
						<input type="checkbox" class="pull-right">
					</label>
				</div><!-- /.form-group -->

				<div class="form-group">
					<label class="control-sidebar-subheading">
						Delete chat history
						<a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
					</label>
				</div><!-- /.form-group -->
			</form>
		</div><!-- /.tab-pane -->
	</div>
</aside>
<!-- /.control-sidebar -->

<!-- Add the sidebar's background. This div must be place immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>



<div id="dw-loading-content" class="alpha60"></div>
<div id="dw-spinner" class="preview dw-corner-all dw-shadow-dark"></div>

<?php echo Tag::js('jquery-1.11.3').PHP_EOL; ?>
<?php echo Tag::js('jQuery-2.1.4.min').PHP_EOL; ?>
<?php echo Tag::js('bootstrap.min').PHP_EOL; ?>
<?php echo Tag::js('jquery.sparkline.min').PHP_EOL; ?>
<?php echo Tag::js('jquery-jvectormap-1.2.2.min').PHP_EOL; ?>
<?php echo Tag::js('jquery-jvectormap-world-mill-en').PHP_EOL; ?>
<?php echo Tag::js('jquery.knob').PHP_EOL; ?>
<?php echo Tag::js('daterangepicker').PHP_EOL; ?>
<?php echo Tag::js('bootstrap-datepicker').PHP_EOL; ?>
<?php echo Tag::js('bootstrap3-wysihtml5.all.min').PHP_EOL; ?>
<?php echo Tag::js('jquery.slimscroll.min').PHP_EOL; ?>
<?php echo Tag::js('fastclick.min').PHP_EOL; ?>
<?php echo Tag::js('app.min').PHP_EOL; ?>
<?php echo Tag::js('dashboard').PHP_EOL; ?>
<?php echo Tag::js('tinymce/tinymce.min').PHP_EOL; ?>
<?php echo Tag::js('demo').PHP_EOL; ?>

<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>

<script>
	$.widget.bridge('uibutton', $.ui.button);
</script>
<?php echo Tag::js('utils/var').PHP_EOL; ?>
<?php echo Tag::js('utils/validador').PHP_EOL; ?>

<script type="text/javascript">
	$(document).ready(function() {
		url = (window.location.hash.lenth >1) ? window.hash : window.location.pathname;
		url = url.split('order')[0].split('pag')[0];
		var activePageSubMenuId;
		var activePageMainMenuElement;
		$(".subnav").each(function (i) {
			if(!$(this).hasClass("hidden")) {
				activePageSubMenuId = $(this).attr("id");
			} else {
				contenedor = $(this).attr('id');
				$(this).find('a').each(function(i) {
					if(url==$(this).attr('href')) {
						$('#'+contenedor).removeClass('hidden');
						$(this).parent().addClass('active');
						$('[data-filter="'+contenedor+'"]').each(function () {
							$(this).parent().addClass('main-nav-arrow active');
							$(this).removeClass('hidden');
							return false;
						});
						return false;
					}
				});
			}
		});
		$(".dropdown-menu").each(function(i) {
			$(this).find('a').each(function(i){
				if(url==$(this).attr('href')) {
					$(this).parent().addClass('active');
					return false;
				}
			});
		});
		$('.dropdown-menu a').on('click', function(){
			este = $(this);
			$(".dropdown-menu a").each(function(i){
				$(this).parents().removeClass('active');
			});
			este.parent().addClass('active');
		});
			//Activa el menú actual
			$(".main-menu-link").each(function (i) {
				if($(this).parent().hasClass("active")){
					activePageMainMenuElement = $(this).attr("id");
				}
			});
			// Habilita el submenú
			$(".main-menu-link").on('click', function(){
				var submenu = $("#" +$(this).attr("data-filter"));
				$(".subnav").each(function (i) {
					$(this).attr("class","subnav hidden");
				});
				submenu.attr("class", "subnav");
				$(".main-menu-link").each(function(i) {
					$(this).parent().removeClass("main-nav-arrow");
				});
				$(this).parent().addClass("main-nav-arrow");
			});
			//Activa el submenú actual
			$('.subnav a').on('click', function(){
				este = $(this);
				$(".subnav li").removeClass('active');
				$(".main-menu-link").parent().removeClass('active');
				este.parent().addClass('active');
				$('.main-nav-arrow').addClass('active');
				//este.parents('div.subnav').removeClass('hidden');
				//$(this).parent().addClass("main-nav-arrow");
			});
			//Activa el menú manualmente
			$('.main-menu-link').on('click', function(){
				if($(this).attr('href').length > 2) {
					$(".main-menu-link").parent().removeClass('active');
					$(this).parent().addClass('active');
				}
			});
		});
$(function() {
	$("[rel=tooltip]").tooltip();
});
</script>

<?php echo DwDialog::alert('Se ha producido un error en la validación del formulario.', 'subtext: Verifica los datos e intenta nuevamente.', 'title: Formulario incorrecto', 'name: errorForm'); ?>
<?php if(PRODUCTION) { ?>
<?php echo DwDialog::alert('Se ha generado la siguiente excepción: <br /><span id="dw-error-ajax"></span>.', 'title: Oops! hemos realizado algo mal.', 'name: errorAjax'); ?>
<?php } else { ?>
<?php echo DwDialog::alert('Se ha generado la siguiente excepción: <br /><span id="dw-error-ajax"></span>.<br /><span id="dw-info-error-ajax"></span>', 'title: Oops! hemos realizado algo mal.', 'name: errorAjax'); ?>
<?php } ?>
<?php echo DwDialog::alert('Usted no posee los permisos necesarios para realizar esta acción.', 'title: Acceso denegado', 'name: accessControl'); ?>