<?php Load::models('personas/persona', 'sistema/usuario'); ?>
<?php $usuario = new Usuario();
$persona = $usuario->getInformacionUsuario(Session::get('id'));
$usuario->fotografia = $persona->fotografia ?>

<header class="main-header">
	<a href="/dashboard" class="logo">
		<span class="logo-mini"><?php echo Html::img('icon.png', 'Soluciones SL') ?></span>
		<span class="logo-lg"><?php echo Html::img('logo2.png', 'Soluciones SL') ?></span>
	</a>

	<nav class="navbar navbar-static-top" role="navigation">
		<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a>
		<div class="navbar-custom-menu">
			<ul class="nav navbar-nav">
				<li class="dropdown messages-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-envelope-o"></i>
						<span class="label label-success">0</span>
						<ul class="dropdown-menu">
							<li class="header">No tienes mensajes por leer</li>
							<ul class="menu">
								<li><a href="#">
									
								</a></li>
							</ul>
							<li class="footer"><a href="">Ver todos los mensajes</a></li>
						</ul>
					</a>
				</li>
				<li class="dropdown notifications-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-bell-o"></i>
						<span class="label label-warning">0</span>
					</a>
				</li>
				<li class="dropdown user user-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<?php echo Html::img("upload/personas/$usuario->fotografia", Session::get('nombre'). ' '  .Session::get('apellido'), 'class="user-image"') ?>
						<span class="hidden-xs"><?php echo (Session::get('nombre'). ' ' . (Session::get('apellido'))); ?></span>
					</a>
					<ul class="dropdown-menu">
						<li class="user-header">
							<?php echo Html::img("upload/personas/$usuario->fotografia", Session::get('nombre'). ' '  .Session::get('apellido'), 'class="img-circle"') ?>
							<p>
								<?php echo (Session::get('nombre'). ' ' . (Session::get('apellido'))); ?> - CEO Soluciones SL
								<small>Miembro fundador Oct. 2003</small>
							</p>
						</li>
						<li class="user-body"></li>
						<li class="user-footer">
							<div class="pull-left">
								<?php echo DwHtml::link('sistema/mi_cuenta/', 'Perfil'); ?>
							</div>
							<div class="pull-right">
								<?php echo DwHtml::link('sistema/login/salir', 'Salir', array('class'=>'no-load'), 'icon-off', FALSE); ?>
							</div>
						</li>
					</ul>
				</li>
				<li>
					<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
				</li>
			</ul>
		</div>
	</nav>
</header>
<aside class="main-sidebar">
	<section class="sidebar">
		<!-- Sidebar user panel (optional) -->
		<div class="user-panel">
			<div class="pull-left image">
				<?php echo Html::img("upload/personas/$usuario->fotografia", Session::get('nombre'). ' '  .Session::get('apellido'), 'class="img-circle"') ?>
			</div>
			<div class="pull-left info">
				<p><?php echo (Session::get('nombre'). ' ' . (Session::get('apellido'))); ?></p>
				<!-- Status -->
				<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		  </div>
		  <form action="#" method="get" class="sidebar-form">
			<div class="input-group">
			  <input type="text" name="q" class="form-control" placeholder="Search...">
			  <span class="input-group-btn">
				<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
			  </span>
			</div>
		  </form>
		  
		<?php DwMenu::load(Menu::BACKEND, Session::get('perfil_id')); ?>
		<?php echo DwMenu::phone(); ?>
	</section>
</aside>


