<?php View::process2($page_module, $page_title, $set_title).PHP_EOL; ?>

<?php View::content() ?>

<div class="gray-bg">
	<div class="fof">
            <!-- 404 error -->
		<div class="container  error-inner wow flipInX">
			<h1>Aviso de Cobro</h1>
			<p class="text-center">Su servicio de Internet presenta retraso en el pago.</p>
			<p class="text-center">Por favor se le pide ponerse al día con el mismo, para evitar las molestias de Corte.</p>
			<p class="text-center">Comuniquese con Administración a tráves del <b>0424-140.36.04</b></p>
			<a class="btn btn-primary" href="/">IR A LA PAGINA PRINCIPAL</a>
		</div>
        <!-- /404 error -->
	</div>
</div>