<?php View::process2($page_module, $page_title, $set_title).PHP_EOL; ?>

<div class="gray-bg">
	<div class="fof">
            <!-- 404 error -->
		<div class="container  error-inner wow flipInX">
			<h1>Servicio Suspendido</h1>
			<p class="text-center">Su servicio de Internet se encuentra <strong>supendido</strong> por falta de pago.</p>
			<p class="text-center">Por favor comuniquese con la administración si piensa que esto es un error.</p>
			<p class="text-center">Comuniquese con Administración a tráves del <b>0424-140.36.04</b></p>
			<a class="btn btn-primary" href="/">IR A LA PAGINA PRINCIPAL</a>
		</div>
        <!-- /404 error -->
	</div>
</div>