<?php View::process2($page_module, $page_title, $set_title).PHP_EOL; ?>

<?php View::content() ?>

<div class="gray-bg">
	<div class="fof">
            <!-- 404 error -->
		<div class="container  error-inner wow flipInX">
			<h1>Lo Sentimos pero estamos teniendo <br /> Problemas en las Conexiones</h1>
			<p class="text-center">Nuestro equipo de soporte tecnico esta trabajando para solventar el problema lo más pronto posible.</p> <p class="text-center">Mientras tanto agradecemos su paciencia.</p>
			<p class="text-center">Comuniquese con Administración a tráves del <b>0424-140.36.04</b></p>
			<a class="btn btn-primary" href="/">IR A LA PAGINA PRINCIPAL</a>
		</div>
        <!-- /404 error -->
	</div>
</div>