<?php View::process2($page_module, $page_title, $set_title).PHP_EOL; ?>

<div class="container">
	<div class="row">
		<div class="col-lg-5">
			
		</div>
		<div class="col-lg-7 about wow fadeInRight">
			<h3>Bienvenido a Soluciones SL</h3>
			<p>Desde 2003 nos esforzamos continuamente para ser más competitivos, mejorar nuestros procesos, y formar a nuestros empleados. En definitiva, rodearnos del mejor equipo posible. Todo ello, para proporcionar las soluciones que necesitan cada uno de nuestros clientes.</p>
			<blockquote>
				<p>
					Nos caracterizamos por prestar distintos servicios de excelente calidad, poniendo a su disposición un personal altamente Calificado y Cualificado en distintas áreas tecnológicas.
				</p>
				<small>CEO Sergio L. Rondón</small>
			</blockquote>
		</div>
	</div>
	<div class="row">
		<div class="hiring">
			<h2 class="wow flipInX">
				Soluciones SL
			</h2>
			<div class="col-lg-4 col-sm-4 about-hiring">
				<div class="content">
					<h3 class="title wow flipInX">
						Historia
					</h3>
					<p><b>Soluciones SL</b> se constituye en 2003 como Consultora Tecnológica, con sede en Ocumare del Tuy, amparada por un equipo profesional especialista en proporcionar y construir soluciones adaptadas a cada negocio.</p> 

					<p>En <b>Soluciones SL</b> ofrecemos desde nuestra fundación un soporte multicanal a clientes, facilitando todos aquellos servicios tecnológicos que puedan necesitar, siendo fiel a la política de proporcionarles todas las soluciones con un único y eficaz proveedor.</p>
				</div>
			</div>
			<div class="col-lg-4 col-sm-4 about-hiring">
				<div class="content">
					<h3 class="title wow flipInX">
						Equipo
					</h3>
					<p>Nuestro equipo está formado por profesionales que aportan un alto nivel humano, un amplio conocimiento técnico, una estricta ética y una filosofía empresarial básica. Nuestra misión es facilitar a nuestros clientes soluciones adaptadas y válidas para su negocio.</p>

					<p>Más allá de estas cualidades, en Soluciones SL reunimos una alta experiencia y formación en diversos campos. A nuestra base, añadimos además una gestión impecable de los proyectos, lo que nos ayuda a conseguir la total satisfacción de nuestros clientes.</p>
				</div>
			</div>
			<div class="col-lg-4 col-sm-4 about-hiring">
				<div class="content">
					<h3 class="title wow flipInX">
						Objetivos
					</h3>
					<p>Nuestra razón de ser es conseguir que los proyectos de nuestros clientes se desarrollen en tiempo y forma excepcional.</p>

					<p>Ayudamos a empresas a ofrecer un mejor servicio, a gestionar con mayor eficacia sus recursos. Todo esto sin dejar de lado el medioambiente.</p>

					<p>Queremos ser partners y socios para nuestros clientes. Una necesidad que el mercado demanda y que nuestros clientes y partners corroboran.</p>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="gray-box">
	<div class="container">
		<div class="row">
			<div class="col-lg-5">
				<div class="about-testimonial boxed-style about-flexslider ">
				<section class="slider wow fadeInRight">
				<div class="flexslider">
					<ul class="slides about-flex-slides">
						<li>
						<div class="about-testimonial-image ">
							<?php echo Html::img('fgoita.png') ?>
						</div>
						<a class="about-testimonial-author" href="#">Freddy R. Goita Cordovés</a>
						<span class="about-testimonial-company">CEO Solutions FG.</span>
						<div class="about-testimonial-content">
							<p class="about-testimonial-quote">
								Donec ut purus sed tortor malesuada venenatis eget eget lorem. Nullam tempor lectus a ligula lobortis pretium. Donec ut purus sed tortor malesuada venenatis eget eget lorem.
							</p>
						</div>
						</li>
						<li>
							<div class="about-testimonial-image ">
								<?php echo Html::img('jrondon.png') ?>
							</div>
							<a class="about-testimonial-author" href="#">José Rondón</a>
							<span class="about-testimonial-company">CEO Telcorp Systems</span>
							<div class="about-testimonial-content">
								<p class="about-testimonial-quote">
									Pellentesque et pulvinar enim. Quisque at tempor ligula. Maecenas augue ante, euismod vitae egestas sit amet, accumsan eu nulla. Nullam tempor lectus a ligula lobortis pretium. Donec ut purus sed tortor malesuada venenatis eget eget lorem.
								</p>
							</div>
						</li>
						<li>
							<div class="about-testimonial-image ">
								<?php echo Html::img('jucean.png') ?>
							</div>
							<a class="about-testimonial-author" href="#">Julio Cesar Andrades</a>
							<span class="about-testimonial-company">Director JUCEAN Fotografias</span>
							<div class="about-testimonial-content">
								<p class="about-testimonial-quote">
									Pellentesque et pulvinar enim. Quisque at tempor ligula. Maecenas augue ante, euismod vitae egestas sit amet, accumsan eu nulla. Nullam tempor lectus a ligula lobortis pretium. Donec ut purus sed tortor malesuada venenatis eget eget lorem.
								</p>
							</div>
						</li>
					</ul>
				</div>
				</section>
			</div>
			</div>
			<div class="col-lg-7" id="skillz">
				<h3 class="skills">Nuestras Habilidades</h3>
				<div class="skill_bar">
					<div class="progress-bar progress-bar-striped active skill_one" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
						<p> &nbsp; Diseños Web : 60% Completados</p>
					</div>
				</div>
				<div class="skill_bar">
					<div class="progress-bar progress-bar-striped active skill_two" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
						<p>&nbsp; Html/CSS : 90% Completados</p>
					</div>
				</div>
				<div class="skill_bar">
					<div class="progress-bar progress-bar-striped active skill_three" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
						<p>&nbsp; Wordpress : 70% Completados</p>
					</div>
				</div>
				<div class="skill_bar">
					<div class="progress-bar progress-bar-striped active skill_four" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 55%">
						<p>&nbsp; Diseños Gráficos : 55% Completados</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>