<?php View::partial('slider') ?>

<div class="container">
	<div class="row mar-b-50">
		<div class="col-md-12">
			<div class="text-center feature-head wow fadeInDown">
				<h1>Algunos Servicios</h1>
			</div>

			<div class="feature-box">
				<div class="col-md-4 col-sm-4 text-center wow fadeInUp">
					<div class="feature-box-heading">
						<em><?=Html::img('1.png', '', 'width="100" height="100"') ?>
						<h4><b>Páginas Multipropósitos</b></h4></em>
					</div>
				</div>

				<div class="col-md-4 col-sm-4 text-center wow fadeInUp">
					<div class="feature-box-heading">
						<em><?=Html::img('2.png', '', 'width="100" height="100"') ?>
						<h4><b>Diseños Adaptables</b></h4></em>
					</div>
				</div>

				<div class="col-md-4 col-sm-4 text-center wow fadeInUp">
					<div class="feature-box-heading">
						<em><?=Html::img('3.png', '', 'width="100" height="100"') ?>
						<h4><b>Alojamiento Web</b></h4></em>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="property gray-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-sm-6 text-center wow fadeInLeft">
				<img src="img/tab1.png" alt="">
			</div>
			<div class="col-lg-6 col-sm-6 wow fadeInRight">
				<h1>Mobile ready</h1>
				<hr>
				<p>
					<i class="fa fa-check fa-lg pr-10"></i>
					Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ablic jiener. natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ablic jiener. natus error sit voluptatem accusantiu.
				</p>
				<p>
					<i class="fa fa-check fa-lg pr-10"></i>
					Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ablic jiener. natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ablic jiener. natus error sit voluptatem accusantiu.
				</p>
				<p>
					<i class="fa fa-check fa-lg pr-10"></i>
					Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ablic jiener.
				</p>
				<hr>
				<a href="javascript:;" class="btn btn-purchase">Purchase now</a>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-lg-6">
			<section class="tab wow fadeInLeft">
				<header class="panel-heading tab-bg-dark-navy-blue">
					<ul class="nav nav-tabs nav-justified ">
						<li class="active">
							<a data-toggle="tab" href="#news">News</a>
						</li>
						<li>
							<a data-toggle="tab" href="#events">Events</a>
						</li>
						<li class="">
							<a data-toggle="tab" href="#notice-board">Notice board</a>
						</li>
					</ul>
				</header>
				<div class="panel-body">
					<div class="tab-content tasi-tab">
						<div id="news" class="tab-pane fade in active">
							<article class="media">
								<a class="pull-left thumb p-thumb"><img src="img/product1.jpg" alt=""></a>
								<div class="media-body b-btm">
									<a href="#" class=" p-head">News Tittle goes here</a>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit.
									</p>
								</div>
							</article>
							<article class="media">
								<a class="pull-left thumb p-thumb"><img src="img/product2.jpg" alt=""></a>
								<div class="media-body b-btm">
									<a href="#" class=" p-head">News Tittle goes here 2</a>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit. simsut dorlor
									</p>
								</div>
							</article>
							<article class="media">
								<a class="pull-left thumb p-thumb">
									<img src="img/product1.jpg" alt="">
								</a>
								<div class="media-body b-btm">
									<a href="#" class=" p-head">
										News Tittle goes here 3
									</a>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit. sumon ahmed
									</p>
								</div>
							</article>
						</div>
						<div id="events" class="tab-pane fade">
							<article class="media">
								<a class="pull-left thumb p-thumb">
									<!--image goes here-->
								</a>
								<div class="media-body b-btm">
									<a href="#" class="cmt-head">
										Lorem ipsum dolor sit amet, consectetur adipiscing elit.
									</a>
									<p>

										<i class="fa fa-time">
										</i>
										1 hours ago
									</p>
								</div>
							</article>
							<article class="media">
								<a class="pull-left thumb p-thumb">
									<!--image goes here-->
								</a>
								<div class="media-body b-btm">
									<a href="#" class="cmt-head">
										Nulla vel metus scelerisque ante sollicitudin commodo
									</a>
									<p>

										<i class="fa fa-time">
										</i>
										23 mins ago
									</p>
								</div>
							</article>
							<article class="media">
								<a class="pull-left thumb p-thumb">
									<!--image goes here-->
								</a>
								<div class="media-body b-btm">
									<a href="#" class="cmt-head">
										Donec lacinia congue felis in faucibus.
									</a>
									<p>

										<i class="fa fa-time">
										</i>
										15 mins ago
									</p>
								</div>
							</article>
						</div>
						<div id="notice-board" class="tab-pane fade">
							<p>
								Notice board goes here Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ablic jiener.
							</p>
							<p>
								Notice board goes here Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ablic jiener.
							</p>
						</div>
					</div>
				</div>
			</section>
		</div>
		<div class="col-lg-6">
			<div class="about-testimonial boxed-style about-flexslider ">
				<section class="slider wow fadeInRight">
					<div class="flexslider">
						<ul class="slides about-flex-slides">
							<li>
								<div class="about-testimonial-image "><?=Html::img('jrondon.png', 'Jose Rondon') ?></div>
								<a class="about-testimonial-author" href="#">José Rondón</a>
								<span class="about-testimonial-company">CEO Telcorp</span>
								<div class="about-testimonial-content">
									<p class="about-testimonial-quote">
										Donec ut purus sed tortor malesuada venenatis eget eget lorem. Nullam tempor lectus a ligula lobortis pretium. Donec ut purus sed tortor malesuada venenatis eget eget lorem.
									</p>
								</div>
							</li>
							<li>
								<div class="about-testimonial-image "><?=Html::img('fgoita.png', 'Freddy Goita') ?></div>
								<a class="about-testimonial-author" href="#">Freddy R. Goita C.</a>
								<span class="about-testimonial-company">CEO Solutions FG</span>
								<div class="about-testimonial-content">
									<p class="about-testimonial-quote">
										Pellentesque et pulvinar enim. Quisque at tempor ligula. Maecenas augue ante, euismod vitae egestas sit amet, accumsan eu nulla. Nullam tempor lectus a ligula lobortis pretium. Donec ut purus sed tortor malesuada venenatis eget eget lorem.
									</p>
								</div>
							</li>
							<li>
								<div class="about-testimonial-image "><?=Html::img('jucean.png', 'Julio C Andrade') ?></div>
								<a class="about-testimonial-author" href="#">Julio Cesar Andrades.</a>
								<span class="about-testimonial-company">CEO Jucean Fotografías				</span>
								<div class="about-testimonial-content">
									<p class="about-testimonial-quote">
										Pellentesque et pulvinar enim. Quisque at tempor ligula. Maecenas augue ante, euismod vitae egestas sit amet, accumsan eu nulla. Nullam tempor lectus a ligula lobortis pretium. Donec ut purus sed tortor malesuada venenatis eget eget lorem.
									</p>
								</div>
							</li>
						</ul>
					</div>
				</section>
			</div>
		</div>
	</div>
</div>

<div class="hr">
	<span class="hr-inner"></span>
</div>

<div class="container">
	<div class="row mar-b-50 our-clients">
		<div class="col-md-3">
			<h2>
				Sistemas usados
			</h2>
			<p>
				Alguno de los sistemas, frameworks, frontend, y sistemas operativos usados para el desarrollo de las aplicaciones.
			</p>
		</div>
		<div class="col-md-9">
			<div class="outside">
				<p>
					<span id="slider-prev">
					</span>
					|
					<span id="slider-next">
					</span>
				</p>
			</div>

			<ul class="bxslider1 clients-list">
				<li>
					<a href="#">
					<?=Html::img('logos/grayapache.png').PHP_EOL; ?>
					<?=Html::img('logos/apache.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/grayphp.png').PHP_EOL; ?>
					<?=Html::img('logos/php.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/graymysql.png').PHP_EOL; ?>
					<?=Html::img('logos/mysql.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/graydebian.png').PHP_EOL; ?>
					<?=Html::img('logos/debian.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/grayispconfig.png').PHP_EOL; ?>
					<?=Html::img('logos/ispconfig.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/graycentos.png').PHP_EOL; ?>
					<?=Html::img('logos/centos.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/graypython.png').PHP_EOL; ?>
					<?=Html::img('logos/python.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/graylinux.png').PHP_EOL; ?>
					<?=Html::img('logos/linux.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/grayperl.png').PHP_EOL; ?>
					<?=Html::img('logos/perl.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/graykumbiaphp.png').PHP_EOL; ?>
					<?=Html::img('logos/kumbiaphp.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/graypftpd.png').PHP_EOL; ?>
					<?=Html::img('logos/pftpd.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/graypostfix.png').PHP_EOL; ?>
					<?=Html::img('logos/postfix.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>
				<li>
					<a href="#">
					<?=Html::img('logos/graybootstrap.png').PHP_EOL; ?>
					<?=Html::img('logos/bootstrap.png', '', 'class="color-img"').PHP_EOL; ?>
					</a>
				</li>


			</ul>


		</div>
	</div>
	<!-- END CLIENTS -->
</div>