<div class="content-wrapper dw-shell-view">
  
        <?php View::process($page_module, $page_title, $set_title); ?>

    <section class="content dw-overflow">
        <?php View::notify(); ?>
    <div class="box box-primary">
        <div class="box-body">

    <div class="dw-overflow">

        <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="form-group">
            <div class="col-md-12">
                <?php echo DwForm::textarea('estado_usuario.descripcion', array('class'=>'form-control input-xxlarge input-required mask-text show-error'), NULL, 'Motivo del cambio de estado'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Actualizar estado'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

        <?php echo DwForm::close(); ?>

    </div>

</div>
</div>
</section>
</div>
