<?php View::process2($page_module, $page_title, $set_title).PHP_EOL; ?>

<div class="container">
	<div class="row">
		<div class="col-lg-3 col-sm-3 address">
		<section class="contact-infos">
		<h4 class="title custom-font text-black">Dirección</h4>
		<?php foreach($sucursales->items as $sucursal):  ?>
		<address>
			<?php echo ($sucursal->ciudad. ' ' .$sucursal->direccion); ?>
			<br>Miranda - Venezuela
			<br>Apartado Postal 1209
		</address>		
		</section>
		<section class="contact-infos">
			<h4 class="title custom-font text-black">Horario</h4>
			<p>
				Lunes a Viernes de 8am a 4pm
				<br>Sábados de 8am a 12pm
				<br>Domingos - Cerrado
				<br>
			</p>
		</section>
		<section class="contact-infos">
			<h4>TELÉFONO</h4>
			<p><i class="icon-phone"></i>+58-424-140.36.04</p>
			<p><i class="icon-phone"> </i>+58-426-112.65.49</p>
		</section>
	<?php endforeach; ?>
		</div>
		<div class="col-lg-1">&nbsp;</div>

		<div class="col-lg-8 col-sm-8 address">
			<h4>Información de Contacto</h4>
			<div><?php echo View::notify() ?></div>
			<div class="contact-form">
			<?php echo DwForm::open("contacto", 'post', 'role="form"', 'id="contact-form"') ?>
					<div class="form-group">
						<label for="name">Nombre</label>
						<?php echo DwForm::text('contact.nombre', array('class'=>'form-control','placeholder'=>'* Coloque su nombre aquí')) ?>
					</div>
					<div class="form-group">
						<label for="email">Correo</label>
						<?php echo DwForm::email('contact.correo', array('class'=>'form-control','placeholder'=>'* Coloque su correo aquí')) ?>
					</div>
					<div class="form-group">
						<label for="phone">Teléfono</label>
						<?php echo DwForm::text('contact.telefono', array('class'=>'form-control','placeholder'=>'* Coloque su correo aquí')) ?>
					</div>
					<div class="form-group">
						<label for="phone">Mensaje</label>
						<?php echo DwForm::textarea('contact.cuerpo', array('rows'=>'5', 'class'=>'form-control')) ?>
					</div>
					<button class="btn btn-primary" type="submit">Enviar</button>
				<?php echo DwForm::close() ?>

			</div>
		</div>
	</div>
</div>

<div class="contact-map">
	<div id="map-canvas" style="width: 100%; height: 400px">
		
	</div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&AMP;sensor=false">
</script>

<script type="text/javascript">
	function initialize() {
		var myLatlng = new google.maps.LatLng(10.105721, -66.767389);
		var mapOptions = {
			zoom: 15,
			center: myLatlng,
			mapTypeId: google.maps.MapTypeId.SATELLITE
		}
		var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
       		var marker = new google.maps.Marker({
			position: myLatlng,
			map: map,
			title: 'Soluciones SL'
		}
                                           );
	}
	google.maps.event.addDomListener(window, 'load', initialize);
</script>