<?php View::process2($page_module, $page_title, $set_title).PHP_EOL; ?>

<div class="container">
	<div class="row">
		<div class="col-md12">
			<h3>Privacidad</h3>
			<p>Todos los datos de carácter personal que se solicitan en la página web, son recabados para la correcta gestión de las actividades de <b>SOLUCIONES SL:</b> gestión de las adhesiones, tramitación de las reclamaciones, atención de consultas, etc. En ningún caso serán utilizados para fines distintos o cedidos a terceros. <B>SOLUCIONES SL</B> está claramente posicionada en contra del "spam", por lo que en ningún caso utilizará los datos personales para el envío de comunicaciones comerciales no solicitadas sin su autorización.</p>
			<p>Los datos de carácter personal que se solicitan en los distintos formularios disponibles en la página web, son incorporados a los ficheros de tratamiento de datos que <b>SOLUCIONES SL</b> tiene convenientemente inscritos en la Agencia de Protección de Datos. Puede consultar la finalidad de la recogida de los datos, así como el número de inscripción de los ficheros, en las páginas en las que figuran dichos cuestionarios.</p>
			<p>&nbsp;</p>
			<h3>Cookies</h3>
			<p>Las cookies son archivos que se pueden descargar en su equipo a través de las páginas web. Son herramientas que tienen un papel esencial para la prestación de numerosos servicios de la sociedad de la información. Entre otros, permiten a una página web almacenar y recuperar información sobre los hábitos de navegación de un usuario o de su equipo y, dependiendo de la información obtenida, se pueden utilizar para reconocer al usuario y mejorar el servicio ofrecido.</p>
			<p><b>Tipos de cookies.</b> Según quien sea la entidad que gestione el dominio desde donde se envían las cookies y trate los datos que se obtengan se pueden distinguir dos tipos: cookies propias y cookies de terceros. Existe también una segunda clasificación según el plazo de tiempo que permanecen almacenadas en el navegador del cliente, pudiendo tratarse de cookies de sesión o cookies persistentes.</p>
			<p>Cookies utilizadas en la web <a href="/">www.solucionessl.com.ve</a>. A continuación se identifican las cookies que están siendo utilizadas en este portal así como su tipología y función.</p>
			<p>La página web utiliza Google Analytics, un servicio de analítica web desarrollada por Google, que permite la medición y análisis de la navegación en las páginas web. En su navegador podrá observar 4 cookies de este servicio. Según la tipología anterior se trata de cookies propias, de sesión y de análisis. Puede encontrar más información al respecto e inhabilitar el uso de estas cookies <a href="https://www.google.co.ve/intl/es/policies/privacy/?fg=1">https://www.google.co.ve/intl/es/policies/privacy/?fg=1</a>.</p>
			<p>A través de la analítica web no se obtiene información sobre sus datos personales garantizando la tutela de la privacidad de las personas que navegan por la web. La información que se obtiene es la relativa al número de usuarios que acceden a la web, el número de páginas vistas, la frecuencia y repetición de las visitas, su duración, el navegador utilizado, el operador que presta el servicio, el idioma, el terminal que utiliza, o la ciudad a la que está asignada su dirección IP. Información que posibilita un mejor y más apropiado servicio por parte de este portal.</p>
			<p><b>Cookies Addhis.</b> Esta web utilitza utiliza el plugin de Social media llamado 'Addthis'  (<a href="http://www.addthis.com/">http://www.addthis.com/</a>) que permite a los usuarios compartir el contenido de nuestra web en diferentes aplicaciones sociales. Si no quiere que 'AddThis' guarde sus cookies en su sistema puede desactivarlo visitando la página <a href="http://www.addthis.com/privacy/opt-out">http://www.addthis.com/privacy/opt-out</a>.</p>
			<p>Otra de las cookies que se descargan de tipo técnico son:</p>
			 <ul class="list-unstyled terms-list">
			 	<li><i class="fa fa-arrow-circle-right pr-10"> </i><b>PHPSESSID</b> necesaria para la correcta navegación por las páginas web.</li>
			 	<li><i class="fa fa-arrow-circle-right pr-10"> </i><b>Language -></b> Para el control del lenguaje seleccionado.</li>
			 </ul>
			 <p>Por último, se descarga una cookie de tipo técnico denominada <b>cookies_policy</b> propia, de tipo técnico y de sesión. Gestiona el consentimiento del usuario ante el uso de las cookies en la página web, con el objeto de evitar la excesiva molestia que pueda suponer mostrar repetidamente información sobre la política de cookies en la parte superior de la web a aquellas personas que hayan aceptado la misma.</p>
			<p>&nbsp;</p>
			<h3>Aceptación de la Política de cookies</h3>
			<p><b>SOLUCIONES SL.,</b> con el objeto de dar cumplimiento a la citada normativa, muestra información sobre su Política de cookies en la parte superior de cualquier página del portal con cada inicio de sesión. Ante esta información es posible llevar a cabo las siguientes acciones:</p>
				<ul class="list-unstyled terms-list">
					<li><i class="fa fa-arrow-circle-right pr-10"> </i><b>Continuar navegando.</b> No se volverá a visualizar este aviso al acceder a cualquier página del portal durante la presente sesión quedando aceptada la política de cookies.</li>
					<li><i class="fa fa-arrow-circle-right pr-10"> </i><b>Restringir las cookies o abandonar la página.</b> Usted puede restringir, bloquear o borrar las cookies de <b>SOLUCIONES SL</b>., o cualquier otra página web, utilizando su navegador. En cada navegador la operativa diferente, la función de 'Ayuda' le mostrará cómo hacerlo, si lo desea puede consultar la operativa desde los links siguientes:</li>
					<li><i class="fa fa-arrow-circle-right pr-10"> </i><b>Internet Explorer:</b> <a href="http://windows.microsoft.com/es-xl/internet-explorer/delete-manage-cookies#ie=ie-10">http://windows.microsoft.com/es-xl/internet-explorer/delete-manage-cookies#ie=ie-10</a>.</li>
					<li><i class="fa fa-arrow-circle-right pr-10"> </i><b>FireFox:</b> <a href="http://support.mozilla.org/es/kb/Borrar%20cookies">http://support.mozilla.org/es/kb/Borrar%20cookies</a>.</li>
					<li><i class="fa fa-arrow-circle-right pr-10"> </i><b>Safari:</b> <a href="www.apple.com/es/privacy/use-of-cookies/">www.apple.com/es/privacy/use-of-cookies/</a></li>
				</ul>
				<p>La Secretaría Técnica es el órgano responsable del tratamiento de los datos dentro de <b>SOLUCIONES SL</b>. Los derechos de acceso, rectificación, cancelación y oposición reconocidos en la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos Personales y en su normativa de desarrollo, deberán ejercerse dirigiendo un escrito y su DNI a la Secretaría de <b>SOLUCIONES SL</b> mediante correo postal a la Secretaría Técnica indicando "Protección de Datos" (Ocumare del Tuy, Urb. Mata de Coco, Bloque No. 27, Piso 4, Apartamento 04-02, de Miranda-Venezuela, 1209), email (<a href="mailto:info@solucionessl.com.ve">info@solucionessl.com.ve</a>) o fax (+58-239-500.01.13).</p>

			<p>&nbsp;</p>
		</div>
	</div>
</div>