<script type="text/javascript">
	function onSend() {
		var bValid = true;
		var tips = $(".dw-validate-tips");
		var login = $("#login");
		var pass = $("#password");
		bValid = bValid && DwCheckLength(tips,login,"El usuario", 3);
		if (bValid) { login.removeClass('error'); }
		bValid = bValid && DwCheckLength(tips, pass,"La contraseña", 5);
		if (bValid) { pass.removeClass('error'); }
		bValid = bValid && DwCheckRegexp(tips, login,/^([A-ZÑ0-9])+$/i, "El usuario debe tener caracteres alfanuméricos.");
		if (bValid) { login.removeClass('error'); }
		bValid = bValid && DwCheckRegexp(tips, pass,/^([A-ZÑ0-9\.\-\#\?\_])+$/i,"La clave debe tener caracteres [A-Z]-[0-9]-[#?.-]");
		if (bValid) { pass.removeClass('error'); }
		if (bValid) { login.removeClass('error');pass.removeClass('error');}
		return bValid;
	}
</script>

<div class="login-bg">

	<div class="container">
	<div class="form-wrapper">

		<?php echo DwForm::open('sistema/login/entrar/', '', array('class'=>'no-ajax dw-validate form-signin wow fadeInUp', 'id'=>'formulario', 'before-send'=>'onSend();')); ?>

			<?php echo DwForm::focus('login'); ?>

			<noscript><h5 style="text-align: center;">¡Tu navegador no soporta Javascript!.. Activa el uso de Javascript en tu navegador.</h5></noscript>

			<h2 class="form-signin-heading">Ingreso al Sistema</h2>

			<div style="" class="dw-validate-tips"></div>
			<div class="login-fields">
				<p>Ingresa tu usuario y contraseña:</p>
				<?php View::notify(); ?>
				<div class="login-wrap">
					<input type="text" id="login" name="login" value="" placeholder="Usuario" class="form-control" />
					<input type="password" id="password" name="password" value="" placeholder="Contraseña" class="form-control"/>
					<label class="checkbox">
					<input type="checkbox" value="remember-me"> Recuerdame
					<span class="pull-right">
						¿Olvido su <?php echo DwHtml::link('#', 'contraseña', array('data-target'=>'#resetPassword', 'data-toggle'=>'modal')); ?>?
					</span>
					</label>
					<?php echo DwDialog::alert('Para recuperar tu contraseña puedes contactar al administrador del sistema o contactarnos a través de los siguientes medios: ', 'subtext: E-mail: info@dailyscript.com.co<br />Teléfono: (+57) 316 240 41 83', 'title: Recuperación de contraseña', 'name: resetPassword', 'icon: icon-question-sign'); ?>
					<div>
						<?php echo DwForm::hidden('mode', null, 'auth'); ?>
					</div>
					<div>
						<?php echo DwForm::token(); ?>
					</div>

				</div>
				<?php echo DwForm::submit2('Ingresar', array('class'=>'btn btn-lg btn-login btn-block'), 'submit'); ?>

				<div class="registration">
					¿No tienes una cuenta todavía? 
					<a class="" href="registration.html">
						Crea una cuenta
					</a>
				</div>

			</div>

		<?php echo DwForm::close(); ?>
	</div>
	</div>

</div>



