<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>mikrotik/usuario/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"mikrotik/usuario/listar/"
        });
    });
</script>

<div class="content-wrapper dw-shell-view">
  
        <?php View::process($page_module, $page_title, $set_title); ?>

    <section class="content dw-overflow">
        <?php View::notify(); ?>
    <div class="box box-primary">
        <div class="box-body">

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("mikrotik/usuario/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th class="col-collapse" data-search="usuario">Usuario</th>
                    <th class="col-collapse" data-search="profile">Perfil Actual</th>
                    <th class="col-collapse" data-search="last-active">Ultima Actividad</th>
                    <th class="col-collapse" data-search="uptime">Actividad Acumulada</th>
                    <th class="btn-actions no-responsive" style="width: 150px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($lista->getAll() as $usuario) : ?>
                
                <tr>
                    <td><?php echo $usuario->getProperty('name') ?></td>
                    <td><?php echo $usuario->getProperty('actual-profile') ?></td>
                    <td><?php echo $usuario->getProperty('last-seen') ?></td>
                    <td><?php echo $usuario->getProperty('uptime-used') ?></td>
                    <td>
                            <?php echo DwHtml::buttonTable('Ver usuario', "mikrotik/usuario/ver/", NULL, 'warning', 'search'); ?>
                            <?php echo DwHtml::buttonTable('Modificar usuario', "mikrotik/usuario/editar/", NULL, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Reactivar usuario', "mikrotik/usuario/estado/reactivar/", NULL, 'danger', 'flag'); ?>
                        </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
    </div>
    </div>
    </section>
</div>